"""Stubbed activities for AI agent execution.

These are placeholder implementations to be replaced with actual logic.
"""

from datetime import datetime

from temporalio import activity

from troller.domain.models.plan import Plan, PlanStep
from troller.worker.workflows.data_structures import Issue


@activity.defn
async def run_planning_agent(issue: Issue) -> Plan:
    """Run the planning agent to generate an implementation plan.

    Args:
        issue: Issue data to plan for.

    Returns:
        Implementation plan generated by the planning agent.
    """
    # Stub implementation - returns mock plan
    steps = [
        PlanStep(
            id="step-1",
            description="Analyze the issue requirements",
            completed=False,
            related_files=None,
            estimated_complexity="simple",
        ),
        PlanStep(
            id="step-2",
            description="Implement the solution",
            completed=False,
            related_files=None,
            estimated_complexity="moderate",
        ),
        PlanStep(
            id="step-3",
            description="Add tests for the implementation",
            completed=False,
            related_files=None,
            estimated_complexity="simple",
        ),
    ]

    return Plan(
        summary=f"Implementation plan for: {issue.title}",
        steps=steps,
        created_at=datetime.now(),
        metadata={"stub": True},
        technical_approach="Use existing patterns in the codebase",
        testing_strategy="Write unit tests using pytest",
    )
