"""Planning-related Temporal activities.

Activities for AI-powered implementation planning.
"""

from pydantic import BaseModel, ConfigDict, Field
from temporalio import activity

from troller.config import config
from troller.domain.models.plan import Plan
from troller.worker.adapters.claude_client import ClaudeClient
from troller.worker.adapters.repo_cloner import RepoCloner
from troller.worker.services.planning_service import PlanningService
from troller.worker.workflows.data_structures import Issue


class PlanningInput(BaseModel):
    """Input parameters for run_planning_agent activity.

    Attributes:
        issue: GitHub issue to create a plan for.
        repo_owner: GitHub repository owner.
        repo_name: GitHub repository name.
        target_branch: Branch to analyze (defaults to main/master if None).
    """

    model_config = ConfigDict(frozen=True)

    issue: Issue = Field(..., description="GitHub issue to create a plan for")
    repo_owner: str = Field(..., description="GitHub repository owner")
    repo_name: str = Field(..., description="GitHub repository name")
    target_branch: str | None = Field(
        default=None, description="Branch to analyze (defaults to main/master if None)"
    )


@activity.defn
async def run_planning_agent(input: PlanningInput) -> Plan:
    """Run the planning agent to generate a codebase-aware implementation plan.

    This activity clones the repository, explores the codebase, generates
    a plan, and cleans up atomically within a single activity execution.

    Args:
        input: Planning parameters including issue and repository info.

    Returns:
        Implementation plan generated by the planning agent.
    """
    # Create adapters and planning service
    claude_client = ClaudeClient(model=config.claude.planning_model)
    repo_cloner = RepoCloner()
    planning_service = PlanningService(claude_client, repo_cloner)

    return await planning_service.generate_plan(
        issue_title=input.issue.title,
        issue_body=input.issue.description,
        issue_number=input.issue.number,
        repo_owner=input.repo_owner,
        repo_name=input.repo_name,
        target_branch=input.target_branch,
    )
