"""Planning-related Temporal activities.

Activities for AI-powered implementation planning.
"""

from temporalio import activity

from troller.domain.models.plan import Plan
from troller.worker.adapters.claude_client import ClaudeClient
from troller.worker.workflows.data_structures import Issue


@activity.defn
async def run_planning_agent(issue: Issue) -> Plan:
    """Run the planning agent to generate an implementation plan.

    Args:
        issue: Issue data to plan for.

    Returns:
        Implementation plan generated by the planning agent.
    """
    client = ClaudeClient()
    return client.generate_plan(
        issue_title=issue.title,
        issue_body=issue.description,
        issue_number=issue.number,
    )
