"""Issue resolution Temporal workflow.

Orchestrates the planning process for GitHub issue resolution.
"""

from datetime import timedelta

from temporalio import workflow
from temporalio.common import RetryPolicy

with workflow.unsafe.imports_passed_through():
    from troller.domain.models.plan import Plan
    from troller.worker.activities.github_activities import (
        FetchIssueInput,
        fetch_issue,
    )
    from troller.worker.activities.planning_activities import run_planning_agent
    from troller.worker.workflows.data_structures import Issue, WorkflowInput


@workflow.defn
class IssueResolutionWorkflow:
    """Workflow that orchestrates issue resolution planning.

    This workflow fetches a GitHub issue, runs the planning agent to generate
    an implementation plan, and stores the plan in workflow state.
    """

    def __init__(self) -> None:
        """Initialize workflow state."""
        self._issue: Issue | None = None
        self._plan: Plan | None = None

    @workflow.run
    async def run(self, input: WorkflowInput) -> Plan:
        """Execute the issue resolution workflow.

        Args:
            input: Workflow input parameters.

        Returns:
            Implementation plan generated by the planning agent.

        Raises:
            ActivityError: If any activity fails.
        """
        # Fetch issue from GitHub
        self._issue = await workflow.execute_activity(
            fetch_issue,
            FetchIssueInput(
                repo_owner=input.repo_owner,
                repo_name=input.repo_name,
                issue_number=input.issue_number,
            ),
            start_to_close_timeout=timedelta(seconds=30),
            retry_policy=RetryPolicy(
                maximum_attempts=3,
                initial_interval=timedelta(seconds=1),
                maximum_interval=timedelta(seconds=10),
            ),
        )

        # Run planning agent (may take a few minutes)
        self._plan = await workflow.execute_activity(
            run_planning_agent,
            args=[self._issue],
            start_to_close_timeout=timedelta(minutes=5),
            retry_policy=RetryPolicy(
                maximum_attempts=3,
                initial_interval=timedelta(seconds=5),
                maximum_interval=timedelta(seconds=30),
            ),
        )

        # Return the plan (guaranteed to be set by activity execution)
        assert self._plan is not None
        return self._plan
