"""PR body builder service.

Pure domain service for building comprehensive PR bodies from plan and commit data.
"""

from troller.domain.models.issue import Issue
from troller.worker.activities.activity_outputs import CommitOutput, PlanOutput


class PRBodyBuilder:
    """Builds formatted PR body content from implementation details.

    This is a pure domain service with no external dependencies.
    It takes domain models and produces a formatted markdown string.
    """

    def build(
        self,
        issue: Issue,
        plan: PlanOutput,
        commits: list[CommitOutput],
    ) -> str:
        """Build comprehensive PR body from implementation details.

        Args:
            issue: The GitHub issue being resolved.
            plan: The implementation plan with steps and approach.
            commits: List of commits made during implementation.

        Returns:
            Formatted markdown string for PR body.
        """
        sections: list[str] = []

        # Issue reference
        sections.append(f"Resolves #{issue.number}")
        sections.append("")

        # Summary section
        sections.append("## Summary")
        sections.append(plan.summary)
        sections.append("")

        # Technical approach (if present)
        if plan.technical_approach:
            sections.append("## Technical Approach")
            sections.append(plan.technical_approach)
            sections.append("")

        # Implementation steps
        sections.append("## Implementation Steps")
        for i, step in enumerate(plan.steps, start=1):
            sections.append(f"{i}. {step.description}")
        sections.append("")

        # Testing strategy (if present)
        if plan.testing_strategy:
            sections.append("## Testing Strategy")
            sections.append(plan.testing_strategy)
            sections.append("")

        # Commits section (if any)
        if commits:
            sections.append("## Commits")
            for commit in commits:
                sections.append(f"- `{commit.sha}` - {commit.message}")
            sections.append("")

        # Footer
        sections.append("---")
        sections.append("🤖 Generated by Troller")

        return "\n".join(sections)
