"""Domain model for implementation plans.

Pure business logic with no external dependencies.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Literal


@dataclass(frozen=True)
class PlanStep:
    """A single step in an implementation plan.

    Attributes:
        id: Unique identifier for the step (e.g., 'step-1', 'step-2').
        description: What this step entails.
        completed: Whether this step has been completed.
        related_files: Files likely to be modified in this step.
        estimated_complexity: Complexity estimate for this step.
    """

    id: str
    description: str
    completed: bool
    related_files: list[str] | None = None
    estimated_complexity: Literal["simple", "moderate", "complex"] | None = None


@dataclass(frozen=True)
class Plan:
    """Implementation plan generated by the planning agent.

    Attributes:
        summary: High-level description of the plan.
        steps: Ordered list of implementation steps.
        created_at: When this plan was created.
        metadata: Extensible metadata for future needs.
        technical_approach: Architecture decisions, libraries, patterns to use.
        testing_strategy: How to test the implementation.
    """

    summary: str
    steps: list[PlanStep]
    created_at: datetime
    metadata: dict[str, Any]
    technical_approach: str | None = None
    testing_strategy: str | None = None
