"""Domain model for implementation plans.

Pure business logic with no external dependencies.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Any


@dataclass(frozen=True)
class PlanStep:
    """A single step in an implementation plan.

    Attributes:
        id: Unique identifier for the step (e.g., 'step-1', 'step-2').
        description: What this step entails.
        completed: Whether this step has been completed.
    """

    id: str
    description: str
    completed: bool


@dataclass(frozen=True)
class Plan:
    """Implementation plan generated by the planning agent.

    Attributes:
        summary: High-level description of the plan.
        steps: Ordered list of implementation steps.
        created_at: When this plan was created.
        metadata: Extensible metadata (issue_number, skill_output, etc.).
    """

    summary: str
    steps: list[PlanStep]
    created_at: datetime
    metadata: dict[str, Any]
